#ifndef VALUE_H
#define VALUE_H

#include "Hardware.h"
// Things need to update when change component

#define MOTOR_1_DIR 1
#define MOTOR_2_DIR -1
#define MOTOR_3_DIR 1
#define MOTOR_4_DIR 1



// FLAME
#define LEFT_FLAME_VALUE 0
#define RIGHT_FLAME_VALUE 0

// COMPASS
#define COMPAA_TYPE ANALOG
#define COMPASS_MAX_VALUE 484;


// SPEED
#define TRACING_BALL_SPEED 10
#define AROUND_BALL_SPEED 10
#define TRACE_VS_AROUND_EYE_VALUE 100

#define TURNING_SPEED 40

//DISTANCE
#define LEFT_DISTANCE_CONVERT_RATIO 5.0/8
#define RIGHT_DISTANCE_CONVERT_RATIO 5.0/8
#define FRONT_DISTANCE_CONVERT_RATIO 5.0/8
#define BACK_DISTANCE_CONVERT_RATIO 5.0/8

//EYE
#define EYE_TYPE ANALOG

//BACKPOSITION
#define BACK_POSITION_SPEED 60
#define HARIZONTAL_CLOSER_RANGE 60
#define HARIZONTAL_FURTHER_RANGE 120
#define VERTICAL_CLOSER_RANGE 35
#define VERTICAL_FURTHER_RANGE 60
#define HORIZONTAL_BLOCK_RANGE 100

//LIGHT
#define LIGHT_NUM 7


#endif
